### ISSUE TITLE
Spec about the floor-plan

### ISSUE THREAD

**Issue by zerg000000** [walkable-server/walkable#154] opened 2019-04-03 02:35 UTC
I hit several times that, making change to floor plan cause a lot of un-obvious exceptions. like `emitter` is mandatory, some options if defined, it must have at least one item. I think a spec maybe useful in this case, make the user experience much better.

**Comment by myguidingstar** [comment] 2019-04-03 03:37
sorry for the experience. I totally agree. The problem is floor plan is quite big, and I've split the processing pipeline into quite a few smaller functions. I guess it will work with spec2's `select` so I am kinda waiting. Without spec2/select, the number of specs can be tremendously large.
That being said, it's still valuable to spec as many of them as possible.

**Comment by zerg000000** [comment] 2019-04-03 05:55
I am totally okay to wait for spec2, as I am waiting for spec2 too.

**Comment by myguidingstar** [comment] 2021-02-21 08:06
New public api has been merged to master. I found a way around with spec1. The public api is simpler, floor-plan now becomes an internal thing.

**Closed** 2021-02-21 08:06 UTC

**Comment by myguidingstar** [comment] 2021-02-21 08:26
to give feedback on errors, guardrails will be used. #87
